#!/bin/bash

VERSION="0.4.2"
DATE="2022-12-15"
NAME="devilbox-cli"
DESCRIPTION="A simple and conveniant command line to manage devilbox from anywhere"
LINK="https://github.com/louisgab/devilbox-cli"

ENV_FILE=".env"

DOCKER_COMPOSE="docker compose"
DOCKER_COMPOSE_FILE="docker-compose.yml"

DEVILBOX_COMPOSE_FILE_PATTERN="${DOCKER_COMPOSE_OVERRIDE_FILE}-"
DEVILBOX_COMPOSE_DIR="compose/"
DEVILBOX_MAIN_CONTAINERS="httpd php mysql pgsql redis memcd mongo"

PHP_CONFIG="PHP_SERVER="
HTTPD_CONFIG="HTTPD_SERVER="
MYSQL_CONFIG="MYSQL_SERVER="
PGSQL_CONFIG="PGSQL_SERVER="
REDIS_CONFIG="REDIS_SERVER="
MEMCD_CONFIG="MEMCD_SERVER="
MONGO_CONFIG="MONGO_SERVER="
DOCROOT_CONFIG="HTTPD_DOCROOT_DIR="
WWWPATH_CONFIG="HOST_PATH_HTTPD_DATADIR="

DEVILBOX_CONTAINERS_CONFIG="DEVILBOX_CONTAINERS="
COMPOSE_PATH_SEPARATOR_CONFIG="COMPOSE_PATH_SEPARATOR="
COMPOSE_FILE_CONFIG="COMPOSE_FILE="
